import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { MainNavbar } from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Toaster } from 'react-hot-toast';
import NextThemeProvider from '@/providers/NextThemeProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased `}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">

        <NextThemeProvider>
            <MainNavbar />
            <main className="grow">
              {children}
            </main>
            <Footer />
            <Toaster />
        </NextThemeProvider>
      </body>
    </html>
  );
}
